#!/bin/sh

numer=0
wyraz=Jarek
wyraz2=$Jarek
wyraz3=\$Jarek
komenda=`wc -l cloud-init.log`  #this is backstick
nowy_numer=`cat numer`

echo numer is $numer
echo wyraz is $wyraz
echo wyraz2 is $wyraz2 and wyraz 3 is $wyraz3
echo output komendy 'wc -l cloud-init.log' = $komenda
echo output komendy 'cat numer' = $nowy_numer
nowy_numer=`expr $nowy_numer + 1`
echo output komendy po ++  = $nowy_numer
echo $nowy_numer > numer
echo "cat numer ->" && cat numer


echo "########################### \n"

#Name display program
if [ $# -eq 0 ]
then
	echo "Name not provided"
else
	echo "Your name is "$1
fi

echo "########################### \n"

#Built-in variables
echo "Number of parameters is $#"  
echo "Program name is $0"
echo "The last command of shell program executed withing the shell program = $?"  
iecho "Parameters as a single string is $*"

echo "########################### \n"

string1="Hello"
string2="Wartość string1  =  $string1"    #zmienna wrzucona
echo $string2
string2='Wartość string1  =  $string1'    #zmienna nie wrzucona
echo $string2

echo "########################### \n"
echo "\n1sza wersja for\n"

echo "Looping @@@@@@@@@ \n"
for loop in numer numer2	#for with listed params
do
	echo $loop
	ls -l $loop
done

echo "\n2ga wersja for\n"

for loop	#for positional params 
do
	echo $loop
	ls -l $loop
done

echo "\nendless loop with while\n"
#while :
#do
#	ls
#done

echo "\nloop with counting\n"
x=1
while [ $x -le 5 ]
do
	x=`expr $x + 1`
	nowy_numer=`expr $nowy_numer + 1`
	echo output loopa = $nowy_numer
done

echo $nowy_numer > numer
echo "cat numer"
cat numer

case $1 in
1 | 2) echo "Numer 1 lub 2";;
*) echo "Cała reszta";;
esac

